ALTER TABLE Article ADD COLUMN IF NOT EXISTS original_url VARCHAR(500) UNIQUE;
ALTER TABLE Article ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Article ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;